/**
 * useCycle13Data.ts — React hook for Cycle 13 character data
 *
 * Fetches static JSON exports from public/data/cycle13/ (generated by
 * scripts/export_cycle13_json.py from cycle13_characters.db).
 *
 * Sentinel verified at export time — the export script confirmed the sentinel at
 *   reincarnated-engine/src/reincarnated/export/cycle13_option_a_loadout_schema_landed.sentinel
 * existed before writing output. The JS consumer cannot read engine-side files directly.
 */
import { useState, useEffect } from 'react';
import type {
  Cycle13Character,
  Cycle13CharactersPayload,
  Cycle13GearInstance,
  Cycle13T4Candidate,
} from '../data/cycle13Types';

// Block A3: node investment limits
export const PASSIVE_MAX = 5;
export const ACTIVE_MAX = 15;
export const T4_BINARY_MAX = 1;

// Block A3: T4 unlock threshold = 70% of chain investment capacity
export const CHAIN_INVESTMENT_MAX = PASSIVE_MAX + ACTIVE_MAX; // 20
export const T4_UNLOCK_THRESHOLD_POINTS = Math.ceil(CHAIN_INVESTMENT_MAX * 0.70); // 14

// ── Types ──────────────────────────────────────────────────────────────────

type Cycle13Status =
  | { status: 'loading' }
  | { status: 'error'; message: string }
  | { status: 'ready'; payload: Cycle13CharactersPayload };

type GearStatus =
  | { status: 'idle' }
  | { status: 'loading' }
  | { status: 'error'; message: string }
  | { status: 'ready'; gear: Cycle13GearInstance[] };

type T4Status =
  | { status: 'idle' }
  | { status: 'loading' }
  | { status: 'error'; message: string }
  | { status: 'ready'; candidates: Cycle13T4Candidate[] };

export interface ChainNodeState {
  chainId: string;        // "t4_chain_1" | "t4_chain_2" | "supporting_chain_1"
  isT4Chain: boolean;
  passive: number;        // current investment (0–5)
  active: number;         // current investment (0–15)
  t4Selected: boolean;    // T4 node selected (0 or 1)
}

// ── Hooks ──────────────────────────────────────────────────────────────────

/** Load all 16 characters + season metadata */
export function useCycle13Characters(): Cycle13Status {
  const [state, setState] = useState<Cycle13Status>({ status: 'loading' });

  useEffect(() => {
    fetch('/data/cycle13/characters.json')
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status} loading cycle13/characters.json`);
        return r.json() as Promise<Cycle13CharactersPayload>;
      })
      .then((data) => {
        if (!data.characters || data.characters.length !== 16) {
          console.warn(
            `WARN [useCycle13Characters] expected 16 characters, got ${data.characters?.length ?? 0}`
          );
        }
        setState({ status: 'ready', payload: data });
      })
      .catch((err: unknown) => {
        setState({ status: 'error', message: String(err) });
      });
  }, []);

  return state;
}

/** Load all 110 gear rows for a selected character */
export function useCycle13Gear(characterId: string | null): GearStatus {
  const [state, setState] = useState<GearStatus>({ status: 'idle' });

  useEffect(() => {
    if (!characterId) {
      setState({ status: 'idle' });
      return;
    }
    setState({ status: 'loading' });
    fetch(`/data/cycle13/gear/${characterId}.json`)
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status} loading gear/${characterId}.json`);
        return r.json() as Promise<Cycle13GearInstance[]>;
      })
      .then((data) => {
        if (data.length !== 110) {
          console.warn(
            `WARN [useCycle13Gear] expected 110 gear rows for ${characterId}, got ${data.length}`
          );
        }
        setState({ status: 'ready', gear: data });
      })
      .catch((err: unknown) => {
        setState({ status: 'error', message: String(err) });
      });
  }, [characterId]);

  return state;
}

/** Load T4 candidates for a selected character */
export function useCycle13T4(characterId: string | null): T4Status {
  const [state, setState] = useState<T4Status>({ status: 'idle' });

  useEffect(() => {
    if (!characterId) {
      setState({ status: 'idle' });
      return;
    }
    setState({ status: 'loading' });
    fetch(`/data/cycle13/t4/${characterId}.json`)
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status} loading t4/${characterId}.json`);
        return r.json() as Promise<Cycle13T4Candidate[]>;
      })
      .then((data) => {
        setState({ status: 'ready', candidates: data });
      })
      .catch((err: unknown) => {
        setState({ status: 'error', message: String(err) });
      });
  }, [characterId]);

  return state;
}

// ── Helpers ────────────────────────────────────────────────────────────────

/** Group gear instances by slot → rarity tier for display */
export function groupGearBySlotAndRarity(
  gear: Cycle13GearInstance[]
): Map<string, Map<string, Cycle13GearInstance>> {
  const map = new Map<string, Map<string, Cycle13GearInstance>>();
  for (const g of gear) {
    if (!map.has(g.slot)) map.set(g.slot, new Map());
    map.get(g.slot)!.set(g.rarity_tier, g);
  }
  return map;
}

/** Build initial chain node state for a character (all investments at 0) */
export function buildInitialChainState(char: Cycle13Character): ChainNodeState[] {
  const { t4_chains, supporting_chains } = char.chain_composition;
  const chains: ChainNodeState[] = [];
  for (let i = 1; i <= t4_chains; i++) {
    chains.push({
      chainId: `t4_chain_${i}`,
      isT4Chain: true,
      passive: 0,
      active: 0,
      t4Selected: false,
    });
  }
  for (let i = 1; i <= supporting_chains; i++) {
    chains.push({
      chainId: `supporting_chain_${i}`,
      isT4Chain: false,
      passive: 0,
      active: 0,
      t4Selected: false,
    });
  }
  return chains;
}

/** Return how many T4 chains are currently at/above the unlock threshold */
export function countUnlockedT4Chains(chains: ChainNodeState[]): number {
  return chains.filter(
    (c) => c.isT4Chain && c.passive + c.active >= T4_UNLOCK_THRESHOLD_POINTS
  ).length;
}

/** Return whether any T4 is currently selected */
export function hasSelectedT4(chains: ChainNodeState[]): boolean {
  return chains.some((c) => c.t4Selected);
}
