/**
 * cosmographData.ts
 * Loads and indexes elrond's Phase 4 cosmograph packet for use at /forge.
 *
 * Data source: /public/data/cosmograph/*.json
 * (Pre-converted from parquet by scripts/convert-cosmograph-data.py)
 *
 * All fetches happen once on /forge mount; results cached in module-level state
 * via the useCosmographData hook.
 */

import type {
  PrimitiveEntry,
  KitConstellation,
  FlagEnumAttachment,
  RegionLabels,
  FactionOverlays,
  ConstellationLayoutData,
} from './cosmographTypes';
import type { TwoLayerLayoutData } from './twoLayerTypes';
import type { RuneLayerLayoutData } from './runeAnchorTypes';

export interface CosmographData {
  primitives: PrimitiveEntry[];
  kits: KitConstellation[];
  flagAttachments: FlagEnumAttachment[];
  regionLabels: RegionLabels;
  factionOverlays: FactionOverlays;

  // Derived indexes for O(1) lookup
  primitiveById: Map<string, PrimitiveEntry>;
  flagsByKitId: Map<string, string[]>; // kit_id → parsed flag list
}

async function loadJson<T>(path: string): Promise<T> {
  const res = await fetch(path);
  if (!res.ok) throw new Error(`Failed to load ${path}: ${res.status} ${res.statusText}`);
  return res.json() as Promise<T>;
}

/**
 * Lazy-load the pre-computed Mode B constellation layout.
 * Called by Forge.tsx when constellation view is first selected.
 * Separate from loadCosmographData() to avoid loading 2MB of layout data
 * for users who only use Mode A (primitive-galaxy).
 *
 * Generated by scripts/compute-constellation-layout.py
 */
export async function loadConstellationLayout(): Promise<ConstellationLayoutData> {
  return loadJson<ConstellationLayoutData>('/data/cosmograph/constellation_layout.json');
}

/**
 * Lazy-load the Phase 3 two-layer + buffer-space layout (baseline: fixed-anchor + radial projection).
 * Called by Forge.tsx when two-layer view is selected.
 * Generated by scripts/compute-twolayer-layout.py
 */
export async function loadTwoLayerLayout(): Promise<TwoLayerLayoutData> {
  return loadJson<TwoLayerLayoutData>('/data/cosmograph/twolayer_layout.json');
}

/**
 * Lazy-load the Phase 3.3 alternative positioning layout (force-directed).
 * Used for algorithm comparison toggle per dispatch § 3.3.
 * Generated by scripts/compute-twolayer-forcealt-layout.py
 */
export async function loadTwoLayerLayoutAlt(): Promise<TwoLayerLayoutData> {
  return loadJson<TwoLayerLayoutData>('/data/cosmograph/twolayer_layout_alt.json');
}

/**
 * Lazy-load the Phase 4 rune-layer layout (rune-per-primitive-group + 6 groups).
 * Generated by scripts/compute-rune-layer-layout.py
 */
export async function loadRuneLayerLayout(): Promise<RuneLayerLayoutData> {
  return loadJson<RuneLayerLayoutData>('/data/cosmograph/rune_layer_layout.json');
}

export async function loadCosmographData(): Promise<CosmographData> {
  const base = '/data/cosmograph';

  const [primitives, kits, flagAttachments, regionLabels, factionOverlays] = await Promise.all([
    loadJson<PrimitiveEntry[]>(`${base}/primitive_registry.json`),
    loadJson<KitConstellation[]>(`${base}/kit_constellations.json`),
    loadJson<FlagEnumAttachment[]>(`${base}/flag_enum_attachments.json`),
    loadJson<RegionLabels>(`${base}/region_labels.json`),
    loadJson<FactionOverlays>(`${base}/faction_overlays.json`),
  ]);

  // Build primitive index
  const primitiveById = new Map<string, PrimitiveEntry>();
  for (const p of primitives) {
    primitiveById.set(p.primitive_id, p);
  }

  // Build flag index: parse flag_set_json once
  const flagsByKitId = new Map<string, string[]>();
  for (const fa of flagAttachments) {
    flagsByKitId.set(fa.kit_id, JSON.parse(fa.flag_set_json) as string[]);
  }

  return {
    primitives,
    kits,
    flagAttachments,
    regionLabels,
    factionOverlays,
    primitiveById,
    flagsByKitId,
  };
}
