/**
 * cycle13Types.ts — TypeScript types for Cycle 13 cycle13_characters.db consumer
 *
 * Mirrors the DB schema documented at reincarnated-loadout/MIGRATION.md §v2.0-cycle-13-option-a-character-db
 * JSON columns are pre-parsed on export; consumers receive typed objects (not raw TEXT).
 *
 * Source DB: reincarnated-loadout/data/cycle13_characters.db (read-only)
 * Static export: public/data/cycle13/ (generated by scripts/export_cycle13_json.py)
 */

// ── Season ─────────────────────────────────────────────────────────────────

export interface Cycle13Season {
  season_id: string;           // "cycle-13-mechanical-season-001"
  cycle: number;               // 13
  wave: string;                // "5 Track B"
  scope: string;               // "endgame_only"
  node: string;                // "L45-50+"
  generated_at: string;        // ISO-8601
  character_count: number;     // 16
  wr_bracket_pass_rate: number;// 0.8889
  methodology_pattern: string | null;
  raw_metadata_json: unknown;
}

// ── BC Tuple ───────────────────────────────────────────────────────────────

export interface Cycle13BcTuple {
  range: string;          // "melee" | "ranged" | "hybrid"
  tempo: string;          // "low" | "medium" | "high"
  amplitude: string;      // "spiky" | "sustained" | "burst"
  attribute: string;      // "STR" | "DEX" | "INT" | "WIS"
  proxy_density: string;  // "none" | "low" | "medium" | "high"
}

export interface Cycle13ChainComposition {
  t4_chains: number;         // number of chains with T4 candidates (1 or 2)
  supporting_chains: number; // number of non-T4 supporting chains
  total_chains: number;      // always 3 for cycle-13
}

// ── Character ──────────────────────────────────────────────────────────────

export interface Cycle13Character {
  character_id: string;    // e.g. "S1_endgame_str_01_heavy_barbarian"
  season_id: string;
  bc_cell_id: string;
  attribute: 'STR' | 'DEX' | 'INT' | 'WIS';
  element: string;         // "fire" | "water" | "earth" | "wind"
  resource_model: 'cooldown' | 'energy' | 'mana' | 'stamina' | 'ki';
  cohort_archetype: 'dps_min_maxer' | 'balanced' | 'defensive' | 'hybrid';
  class_chain_count: number; // 3
  t4_scope: string | null;   // "character_wide" | "chain_wide_own" | "chain_wide_parallel" | null
  scope_downscale_factor: number | null;
  wr_bracket_pass: 0 | 1;
  bc_tuple: Cycle13BcTuple;
  chain_composition: Cycle13ChainComposition;
  wr_bracket_details: { note: string; total_legendaries_validated: number } | null;
}

// ── T4 Candidate ───────────────────────────────────────────────────────────

export interface Cycle13ScopeProjectionData {
  [scope: string]: {
    weighted_score: number;
    net_synergy_score: number;
    prior_weight: number;
    scope_amplification_9_warn: boolean;
    scope_amplification_10_warn: boolean;
  };
}

export interface Cycle13T4Candidate {
  candidate_id: string;
  character_id: string;
  season_id: string;
  category_a_strategy: string;     // e.g. "DEFENSIVE_CONVERSION"
  category_bc_strategy: string;    // e.g. "ELEMENT_CONVERSION"
  t4_category_bc: 'A' | 'B' | 'C';
  is_class_wide_trade_off: 0 | 1;
  secondary_element: string | null;
  magnitude_tier: string | null;
  magnitude_midpoint: number | null;
  parallel_chain_mode: 'own_chain' | 'parallel';
  target_chain_id: string | null;
  resolve_score: number;
  create_score: number;
  net_synergy_score: number;
  synergy_eligible: 0 | 1;
  retries_used: number;
  pattern_9_warn: 0 | 1;
  pattern_10_warn: 0 | 1;
  is_active: 0 | 1;
  separability_pass: 0 | 1;
  t4_scope: string | null;
  scope_downscale_factor: number | null;
  scope_prior_weight: number | null;
  scope_weighted_score: number | null;
  scope_projection_data: Cycle13ScopeProjectionData | null;
  category_a_params: Record<string, unknown>;
  category_bc_params: Record<string, unknown>;
}

// ── Gear Instance ──────────────────────────────────────────────────────────

export type Cycle13Slot =
  | 'main_weapon' | 'secondary_item' | 'head' | 'chest'
  | 'hands' | 'feet' | 'legs' | 'amulet' | 'ring_1' | 'ring_2' | 'belt';

export type Cycle13RarityTier =
  | 'common' | 'uncommon' | 'rare' | 'epic'
  | 'legendary_t0' | 'legendary_t0_5' | 'legendary_t1' | 'legendary_t2'
  | 'set_t1' | 'set_t2';

export interface PartitionModifier {
  modifier_id: string;
  category: string;          // "damage" | "crit" | "resource" | "res_pen" | "speed" | "on_trigger" | ...
  modifier_polarity: string; // "prefix" | "suffix"
  tier_restriction: string;  // "none" | "epic_plus" | ...
  magnitude: number;
  resource_model_filter: string | null;
}

export interface CapabilityModifier {
  modifier_id: string;
  capability_category: string; // "spatial_adjusting" | ...
  slot_restriction: string;    // "any" | specific slot
  chain_alignment: string | null;
}

export interface T4Annotation {
  chain_alignment: string;    // e.g. "t4_chain_1"
  t4_target_intent: string;   // e.g. "earth"
  attunement_count: number;
  scope_preference: string;   // e.g. "character_wide"
}

export interface SetBonus {
  set_id: string;
  bonus_2pc_effect_tag: string;
  bonus_4pc_effect_tag: string;
  scope_preference: string;
}

export interface TriggeredPassive {
  pattern_id: string;
  slot_family: string;
  description: string;
  is_true_active: boolean;
  probability_at_rarity: number;
}

export interface Cycle13GearInstance {
  gear_instance_id: string;
  character_id: string;
  season_id: string;
  slot: Cycle13Slot;
  rarity_tier: Cycle13RarityTier;
  rarity_tier_order: number; // 0-9
  partition_modifiers: PartitionModifier[];
  capability_modifiers: CapabilityModifier[];
  t4_annotation: T4Annotation | null;   // non-null from legendary_t1 up
  set_bonus: SetBonus | null;           // non-null for set_t1/set_t2 only
  set_bonus_rank: number;
  is_unique: 0 | 1;
  triggered_passive: TriggeredPassive | null;
}

// ── Static export payload ──────────────────────────────────────────────────

export interface Cycle13CharactersPayload {
  season: Cycle13Season;
  characters: Cycle13Character[];
}

// ── Rarity display helpers ─────────────────────────────────────────────────

export const RARITY_LABEL: Record<Cycle13RarityTier, string> = {
  common:          'Common',
  uncommon:        'Uncommon',
  rare:            'Rare',
  epic:            'Epic',
  legendary_t0:    'Legendary T0',
  legendary_t0_5:  'Legendary T0.5',
  legendary_t1:    'Legendary T1',
  legendary_t2:    'Legendary T2',
  set_t1:          'Set T1',
  set_t2:          'Set T2',
};

export const RARITY_COLOR: Record<Cycle13RarityTier, string> = {
  common:          'text-gray-400 border-gray-600',
  uncommon:        'text-green-400 border-green-700',
  rare:            'text-blue-400 border-blue-700',
  epic:            'text-purple-400 border-purple-700',
  legendary_t0:    'text-amber-400 border-amber-700',
  legendary_t0_5:  'text-amber-300 border-amber-600',
  legendary_t1:    'text-orange-300 border-orange-500',
  legendary_t2:    'text-orange-200 border-orange-400',
  set_t1:          'text-emerald-300 border-emerald-500',
  set_t2:          'text-emerald-200 border-emerald-400',
};

export const SLOT_LABEL: Record<Cycle13Slot, string> = {
  main_weapon:    'Main Weapon',
  secondary_item: 'Off-Hand',
  head:           'Head',
  chest:          'Chest',
  hands:          'Hands',
  feet:           'Feet',
  legs:           'Legs',
  amulet:         'Amulet',
  ring_1:         'Ring 1',
  ring_2:         'Ring 2',
  belt:           'Belt',
};

export const SLOT_ORDER: Cycle13Slot[] = [
  'main_weapon', 'secondary_item', 'head', 'chest', 'hands',
  'feet', 'legs', 'amulet', 'ring_1', 'ring_2', 'belt',
];

export const RARITY_ORDER: Cycle13RarityTier[] = [
  'common', 'uncommon', 'rare', 'epic',
  'legendary_t0', 'legendary_t0_5', 'legendary_t1', 'legendary_t2',
  'set_t1', 'set_t2',
];

/** Capability toolkit threshold: legendary_t0 and above have capability_modifiers */
export function hasCapabilityToolkit(tier: Cycle13RarityTier): boolean {
  return ['legendary_t0', 'legendary_t0_5', 'legendary_t1', 'legendary_t2', 'set_t1', 'set_t2'].includes(tier);
}

/** T4 annotation threshold: legendary_t1 and above */
export function hasT4Annotation(tier: Cycle13RarityTier): boolean {
  return ['legendary_t1', 'legendary_t2', 'set_t1', 'set_t2'].includes(tier);
}

/** Derive human-readable display name from character_id */
export function deriveCharacterDisplayName(characterId: string): string {
  // e.g. "S1_endgame_str_01_heavy_barbarian" → "Heavy Barbarian"
  const parts = characterId.split('_');
  // Find the part after the 2-digit index (e.g., "01")
  const indexIdx = parts.findIndex((p) => /^\d{2}$/.test(p));
  if (indexIdx >= 0 && indexIdx < parts.length - 1) {
    return parts
      .slice(indexIdx + 1)
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
      .join(' ');
  }
  return characterId;
}

/** T4 Block A3: per-node max investment by type */
export const NODE_MAX: Record<'passive' | 'active' | 't4', number> = {
  passive: 5,
  active:  15,
  t4:      1,
};

/** T4 Block A3: 70% threshold for T4 unlock */
export const T4_UNLOCK_THRESHOLD = 0.70;
